<option value="K00 Disorders of tooth development and eruption">K00 Disorders of tooth development and eruption</option> 
<option value="K00.0 Anodontia">K00.0 Anodontia</option> 
<option value="K00.00 Partial anodontia [hypodontia] [oligodontia]">K00.00&nbsp;&nbsp;&nbsp;&nbsp;Partial anodontia [hypodontia] [oligodontia]</option> 
<option value="K00.01 Total anodontia">K00.01&nbsp;&nbsp;&nbsp;&nbsp;Total anodontia</option> 
<option value="K00.09 Anodontia, unspecified">K00.09&nbsp;&nbsp;&nbsp;&nbsp;Anodontia, unspecified</option>  
<option value="K00.l Supernumerary teeth">K00.l Supernumerary teeth</option>  
<option value="Excludes: impacted supernumerary teeth (K01.18)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Excludes: impacted supernumerary teeth (K01.18)</option>  
<option value="K00.10 Incisor 'and canine regions">K00.10&nbsp;&nbsp;&nbsp;&nbsp;Incisor 'and canine regions</option> 
<option value="Mesiodens">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Mesiodens</option> 
<option value="K00.11 Premolar region">K00.11&nbsp;&nbsp;&nbsp;&nbsp;Premolar region</option>  
<option value="K00.12 Molar region">K00.12&nbsp;&nbsp;&nbsp;&nbsp;Molar region</option> 
<option value="Distomolar, Fourth Molar, Paramolar">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Distomolar, Fourth Molar, Paramolar</option> 
<option value="K00.19 Supernumerary teeth, unspecified">K00.19&nbsp;&nbsp;&nbsp;&nbsp;Supernumerary teeth, unspecified</option> 
<option value="K00.2 Abnormalities of size and form of teeth">K00.2 Abnormalities of size and form of teeth</option> 
<option value="K00.20 Macrodontia">K00.20&nbsp;&nbsp;&nbsp;&nbsp;Macrodontia</option> 
<option value="K00.21 Microdontia ">K00.21&nbsp;&nbsp;&nbsp;&nbsp;Microdontia </option> 
<option value="K00.23 Fusion and gemination ">K00.23&nbsp;&nbsp;&nbsp;&nbsp;Fusion and gemination </option> 
<option value="K00.24 Dens evaginatus (occlusal tuberculum)">K00.24&nbsp;&nbsp;&nbsp;&nbsp;Dens evaginatus (occlusal tuberculum) </option> 
<option value="K00.25 Dens invaginatus (dens in dente) and incisal anomalies">K00.25&nbsp;&nbsp;&nbsp;&nbsp;Dens invaginatus (dens in dente) and incisal anomalies </option> 
<option value="Palatal groove ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Palatal groove </option> 
<option value="Peg-shaped incisors ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Peg-shaped incisors </option> 
<option value="Shovel-shaped incisors ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shovel-shaped incisors </option> 
<option value="K00.28 Taurodontism ">K00.28&nbsp;&nbsp;&nbsp;&nbsp;Taurodontism </option> 
<option value="K00.29 Other unspecified abnormalities of size and form of teeth">K00.29&nbsp;&nbsp;&nbsp;&nbsp;Other unspecified abnormalities of size and form of teeth </option> 
<option value="K00.3 Mottled teeth">K00.3 Mottled teeth</option> 
<option value="K00.30 Endemic mottling of enamel (fluorosis) ">K00.30&nbsp;&nbsp;&nbsp;&nbsp;Endemic mottling of enamel (fluorosis) </option> 
<option value="K00.31 Non-endemic mottling of enamel (non-fluoride enamel opacities) ">K00.31&nbsp;&nbsp;&nbsp;&nbsp;Non-endemic mottling of enamel (non-fluoride enamel opacities) </option> 
<option value="K00.39 Mottled teeth, unspecified">K00.39&nbsp;&nbsp;&nbsp;&nbsp;Mottled teeth, unspecified </option> 
<option value="K00.4 Disturbances in tooth formation">K00.4 Disturbances in tooth formation </option> 
<option value="K00.40 Enamel hypoplasia">K00.40&nbsp;&nbsp;&nbsp;&nbsp;Enamel hypoplasia </option> 
<option value="K00.49 Disturbance in tooth formation, unspecified">K00.49&nbsp;&nbsp;&nbsp;&nbsp;Disturbance in tooth formation, unspecified </option> 


<option value="K00.6 Disturbances in tooth. eruption">K00.6 Disturbances in tooth. eruption </option>
<option value="K00.63 Retained (persistent) primary (deciduous) teeth">K00.63&nbsp;&nbsp;&nbsp;&nbsp;Retained (persistent) primary (deciduous) teeth</option>
<option value="K00.69 Disturbance in tooth eruption, unspecified">K00.69&nbsp;&nbsp;&nbsp;&nbsp;Disturbance in tooth eruption, unspecified </option>
<option value="K00.8 Other disorders of tooth development">K00.8 Other disorders of tooth development </option>
<option value="K00.83 Colour changes during tooth formation due to tetracyclines ">K00.83&nbsp;&nbsp;&nbsp;&nbsp;Colour changes during tooth formation due to tetracyclines </option>
<option value="K01 Embedded and impacted teeth">K01 Embedded and impacted teeth </option>
<option value="K01.0 Embedded teeth">K01.0 Embedded teeth </option>
<option value="An embedded tooth is a tooth that has failed to erupt without obstruction by another tooth.">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An embedded tooth is a tooth that has failed to erupt without obstruction by another tooth. </option>
<option value="K01.1 Impacted teeth">K01.1&nbsp;&nbsp;&nbsp;&nbsp;Impacted teeth </option>
<option value="An impacted tooth is a tooth that has failed to erupt because of obstruction by another tooth.">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;An impacted tooth is a tooth that has failed to erupt because of obstruction by another tooth. </option>
<option value="K01.12 Maxillary canine ">K01.12&nbsp;&nbsp;&nbsp;&nbsp;Maxillary canine </option>
<option value="K01.13 Mandibular canine">K01.13&nbsp;&nbsp;&nbsp;&nbsp;Mandibular canine </option>
<option value="K01.16 Maxillary molar ">K01.16&nbsp;&nbsp;&nbsp;&nbsp;Maxillary molar </option>
<option value="K01.17 Mandibular molar ">K01.17&nbsp;&nbsp;&nbsp;&nbsp;Mandibular molar </option>
<option value="K01.18 Supernumerary tooth ">K01.18&nbsp;&nbsp;&nbsp;&nbsp;Supernumerary tooth </option>
<option value="K01.19 Impacted tooth, unspecified">K01.19&nbsp;&nbsp;&nbsp;&nbsp;Impacted tooth, unspecified </option>
<option value="K02 Dental caries ">K02&nbsp;&nbsp;&nbsp;&nbsp;Dental caries </option>
<option value="K02.0 Caries limited to enamel">K02.0&nbsp;&nbsp;&nbsp;&nbsp;Caries limited to enamel</option>
<option value="White spot lesion (intial caries)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;White spot lesion (intial caries) </option>
<option value="K02.1 Caries extending into dentine ">K02.1&nbsp;&nbsp;&nbsp;&nbsp;Caries extending into dentine </option>
<option value="K02.2 Caries of cementum ">K02.2&nbsp;&nbsp;&nbsp;&nbsp;Caries of cementum </option>
<option value="K02.9 Dental caries, unspecifted ">K02.9&nbsp;&nbsp;&nbsp;&nbsp;Dental caries, unspecifted </option>
<option value="K03 Other diseases of hard tissues of teeth">K03 Other diseases of hard tissues of teeth</option>
<option value="Excludes: dental caries (K02.-) teeth-grinding (F45.8)">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Excludes: dental caries (K02.-) teeth-grinding (F45.8) </option>
<option value="K03.0 Excessive attrition of teeth ">K03.0 Excessive attrition of teeth </option>
<option value="K03.00 Occlusal ">K03.00&nbsp;&nbsp;&nbsp;&nbsp;Occlusal </option>
<option value="K03.01 Approximal ">K03.01&nbsp;&nbsp;&nbsp;&nbsp;Approximal </option>
<option value="K03.09 Attrition of teeth, unspecified">K03.09&nbsp;&nbsp;&nbsp;&nbsp;Attrition of teeth, unspecified</option>
<option value="K03.1 Abrasion of teeth ">K03.1	Abrasion of teeth </option>
<option value="K03.10 Dentifrice">K03.10	Dentifrice</option>
<option value="Wedge defect NOS ">&nbsp;&nbsp;&nbsp;&nbsp;Wedge defect NOS </option>
<option value="K03.13	Traditional">K03.13	Traditional</option>
<option value="Ritual">&nbsp;&nbsp;&nbsp;&nbsp;Ritual </option>
<option value="K03.19	Abrasion of teeth, unspecified">K03.19	Abrasion of teeth, unspecified </option>
<option value="K03.2 Erosion of teeth	">K03.2 Erosion of teeth	</option>
<option value="K03.29 Erosion of teeth, unspeciftied">K03.29 Erosion of teeth, unspeciftied </option>
<option value="K03.3 Pathological resorption of teeth">K03.3 Pathological resorption of teeth </option>
<option value="K03.30 External">K03.30&nbsp;&nbsp;&nbsp;&nbsp;External </option>
<option value="K03.31 Internal (internal granuloma) (pink spot) ">K03.31&nbsp;&nbsp;&nbsp;&nbsp;Internal (internal granuloma) (pink spot) </option>
<option value="K03.39 Pathological resorption ofteeth, unspecifted">K03.39&nbsp;&nbsp;&nbsp;&nbsp;Pathological resorption ofteeth, unspecifted</option> 
<option value="K03.4 Hypercementosis ">K03.4 Hypercementosis </option>
<option value="Excludes: hypercementosis in Paget's disease ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Excludes: hypercementosis in Paget's disease </option>
<option value="K03.5 Ankylosis of teeth">K03.5 Ankylosis of teeth</option>
<option value="K03.6 Deposits (accretions) on teeth">K03.6 Deposits (accretions) on teeth </option>
<option value="K03.61 Due to tabacco habit ">K03.61&nbsp;&nbsp;&nbsp;&nbsp;Due to tabacco habit </option>
<option value="K03.64 Supragingival calculus ">K03.64&nbsp;&nbsp;&nbsp;&nbsp;Supragingival calculus </option>
<option value="K03.65 Subgingival calculus ">K03.65&nbsp;&nbsp;&nbsp;&nbsp;Subgingival calculus </option>
<option value="K03.66 Dental plaque ">K03.66&nbsp;&nbsp;&nbsp;&nbsp;Dental plaque </option>
<option value="K03.69 Deposit on teeth, unspecified ">K03.69&nbsp;&nbsp;&nbsp;&nbsp;Deposit on teeth, unspecified </option>
<option value="K03.7 Posteruptive colour changes of dental hard tissues">K03.7 Posteruptive colour changes of dental hard tissues	</option>
<option value="K03.71 Due to pulpal bleeding ">K03.71&nbsp;&nbsp;&nbsp;&nbsp;Due to pulpal bleeding </option>
<option value="K03.79 Colour change, unspecified ">K03.79&nbsp;&nbsp;&nbsp;&nbsp;Colour change, unspecified </option>
<option value="K03.8 Other specified diseases of hard tissues of teeth ">K03.8 Other specified diseases of hard tissues of teeth </option>
<option value="K03.80 Sensitive dentine">K03.80&nbsp;&nbsp;&nbsp;&nbsp;Sensitive dentine</option>
<option value="K04 Diseases of pulp and periapical tissues ">K04 Diseases of pulp and periapical tissues </option>
<option value="K04.0 Pulpitis">K04.0 Pulpitis</option>
<option value="K04.01 Acute">K04.01&nbsp;&nbsp;&nbsp;&nbsp;Acute</option>
<option value="K04.03 Chronic">K04.03&nbsp;&nbsp;&nbsp;&nbsp;Chronic</option>
<option value="K04.09 Pulpitis, unspecified ">K04.09&nbsp;&nbsp;&nbsp;&nbsp;Pulpitis, unspecified </option>
<option value="K04.1 Necrosis of pulp">K04.1 Necrosis of pulp</option>
<option value="K04.2 Pulp degeneration">K04.2 Pulp degeneration</option>
<option value="K04.5 Chronic apical periodontitis">K04.5 Chronic apical periodontitis</option>
<option value="K04.7 Periapical abscess without sinus">K04.7 Periapical abscess without sinus</option> 

<option value="K04.8 Radicular cyst">K04.8 Radicular cyst</option>
<option value="K04.80 Apical and lateral ">K04.80 	Apical and lateral </option>
<option value="K04.81 Residual ">K04.81 	Residual </option>
<option value="K04.89 Radicular cyst, unspecified">K04.89 	Radicular cyst, unspecified </option>
<option value="K05 Gingivitis and periodontal diseases ">K05  Gingivitis and periodontal diseases </option>
<option value="K05.0 Acute gingivitis ">K05.0 Acute gingivitis </option>
<option value="Excludes: acute pericoronitis (K05.22) acute necrotizing ulcerative gingivitis (fusospirochaetal .gingivitis) (Vincent'sgingivitis) (A69.1O) herpesviral gingivostomatitis (BOO .2X)">Excludes: acute pericoronitis (K05.22) acute necrotizing ulcerative gingivitis (fusospirochaetal .gingivitis) (Vincent'sgingivitis) (A69.1O) herpesviral gingivostomatitis (BOO .2X)</option> 
<option value="K05.00 Acute streptococcal gingivostomatitis">K05.00	Acute streptococcal gingivostomatitis</option>
<option value="K05.09 Acute gingivitis, unspecified ">K05.09	Acute gingivitis, unspecified </option>
<option value="K05.1 Chronic gingivitis ">K05.1  Chronic gingivitis </option>
<option value="K05.10 Simple marginal ">K05.10 	Simple marginal </option>
<option value="K05.11 Hyperplastic ">K05.11 	Hyperplastic </option>
<option value="K05.19 Chronic gingivitis, unspecified ">K05.19 	Chronic gingivitis, unspecified </option>
<option value="K05.2 Acute periodontitis">K05.2  Acute periodontitis</option>
<option value="K05.20 Periodontal abscess( parodontal abscess) of gingival origin without sinus">K05.20		Periodontal abscess( parodontal abscess) of gingival origin without sinus</option>
<option value="K05.22 Acute pericoronitis">K05.22		Acute pericoronitis</option>
<option value="K05.29 Acute periodontitis, unspecified">K05.29		Acute periodontitis, unspecified</option>
<option value="K05.3 Chronic periodontitis">K05.3	 Chronic periodontitis </option>
<option value="K05.30 Simplex ">K05.30 	Simplex </option>
<option value="K05.31 Complex ">K05.31 	Complex </option>
<option value="K05.32 Chronic pericoronitis">K05.32 	Chronic pericoronitis </option>
<option value="K05.39 Chronic periodontitis, unspecified">K05.39 	Chronic periodontitis, unspecified </option>
<option value="K06 Other disorders of gingiva and edentulous alveolar ridge">K06 	Other disorders of gingiva and edentulous alveolar ridge</option>
<option value="K06.0 Gingival recession">K06.0 Gingival recession</option>
<option value="K06.09 Gingival recession, unspecified">K06.09 Gingival recession, unspecified</option>
<option value="K06.1 ingival enlargement">K06.1	Gingival enlargement</option>
<option value="K06.19 Gingival enlargement, unspecified">K06.19		Gingival enlargement, unspecified</option>
<option value="K06.2 Gingival and edentulous alveolar ridge lesions associated with trauma ">K06.2	 Gingival and edentulous alveolar ridge lesions associated with trauma </option>
<option value="K06.20 Due to traumatic occlusion ">K06.20 	Due to traumatic occlusion </option>
<option value="K06.21 Due to toothbrushing ">K06,21 	Due to toothbrushing </option>
<option value="K06.23 Irritative hyperplasia (denture hyperplasia) ">K06.23 	Irritative hyperplasia (denture hyperplasia) </option>
<option value="K06.29 Unspecified gingival and edentulous alveolar ridge lesions associated with trauma ">K06.29 	Unspecified gingival and edentulous alveolar ridge lesions associated with trauma </option>
<option value="K07 Dentofacial anomalies (including malocclusion">K07  Dentofacial anomalies (including malocclusion)</option>
<option value="K07.2  Anomalies of dental arch relationship ">K07.2  Anomalies of dental arch relationship </option>
<option value="K07.22 Excessive overjet (horizontal overbite)">K07.22 	Excessive overjet (horizontal overbite) </option>
<option value="K07.23 Excessive overbite (vertical overbite) ">K07.23 	Excessive overbite (vertical overbite) </option>
<option value="K07.24 Openbite ">K07.24 	Openbite </option>
<option value="K07.25 Crossbite (anterior, posterior) ">K07.25 	Crossbite (anterior, posterior) </option>
<option value="K07.3 Anomalies of tooth position ">K07.3  Anomalies of tooth position </option>
<option value="K07.30 Crowding ">K07.30 	Crowding </option>
<option value="K07.33 Spasing ">K07.33  	Spasing </option>
<option value="Diastema">Diastema </option>
<option value="K07.35 Embedded or impacted teeth in abnormal position ">K07.35 Embedded or impacted teeth in abnormal position </option>
<option value="Excludes: embedded or impacted teth in normal (K01.0, K01.1) ">Excludes: embedded or impacted teth in normal (K01.0, K01.1) </option>
<option value="K07.6 Temporomandibular joint disorders">K07.6 Temporomandibular joint disorders </option>
<option value="K07.60 Temporomandibular joint-pain-dysfunction syndrome (Costen) ">K07.60	Temporomandibular joint-pain-dysfunction syndrome (Costen) </option>
<option value="K07.61 Clicking (snapping) jaws ">K07.61	Clicking (snapping) jaws </option>
<option value="K07.62 Recurrent dislocation and subluxation of temporomandibular joint ">K07.62	Recurrent dislocation and subluxation of temporomandibular joint </option>
<option value="K07.63 Pain in temporomandibular joint, not elsewhere classified">K07.63	Pain in temporomandibular joint, not elsewhere classified</option>
<option value="K07.64 Stiffness of temporomandibular joint, not elsewhere classified">K07.64	Stiffness of temporomandibular joint, not elsewhere classified </option>
<option value="K07.65 Osteophyte of temporomandibular joint">K07.65	Osteophyte of temporomandibular joint</option>
<option value="K07.69 Temporomandibular joint disorder, unspecified">K07.69	Temporomandibular joint disorder, unspecified </option>
<option value="K08 Other disorders of teeth and supporting structures">K08 Other disorders of teeth and supporting structures</option>
<option value="K08.1 Loss of teeth due to accident, extraction or local periodontal disease">K08.1 Loss of teeth due to accident, extraction or local periodontal disease </option>
<option value="K08.2 Atrophy of edentulous alveolar ridge">K08.2 Atrophy of edentulous alveolar ridge </option>
<option value="K08.3 Retained dental roo">K08.3 Retained dental root </option>
<option value="K09 Cysts of oral region, not elsewhere classified">K09 . Cysts of oral region, not elsewhere classified</option>
<option value="Excludes: radicular cyst (K04.8) mucous cyst (Kl1.6)">Excludes: radicular cyst (K04.8) mucous cyst (Kl1.6) </option>
<option value="K09.12 Nasopalatine (incisive canal)">K09.12	Nasopalatine (incisive canal) </option>
<option value="K10 Other diseases of jaws ">K10 	Other diseases of jaws </option>
<option value="K10.0 Developmental disorders of jaws">K10.0 Developmental disorders of jaws </option>
<option value="K10.00 Torus mandibularis">K10.00 	Torus mandibularis </option>
<option value="K10.01 Torus palatinus">K10.01 	Torus palatinus </option>
<option value="K10.2 Inflammatory conditions of jaws">K10.2 	Inflammatory conditions of jaws </option>
<option value="K10.20 Osteitis of jaw ">K10.20 	Osteitis of jaw </option>
<option value="K10.21 Osteomyelitis of jaw">K10.21 	Osteomyelitis of jaw </option>
<option value="K10.3 Alveolitis of jaws ">K10.3		Alveolitis of jaws </option>
<option value="K11 Diseases of salivary glands">K11 	Diseases of salivary glands </option>
<option value="K11.7 Disturbances of salivary secretion ">K11.7	Disturbances of salivary secretion </option>
<option value="Excludes: dry mouth NOS (R68.2) sicca syndrome (Sjogren) (M35.0)">Excludes: dry mouth NOS (R68.2) sicca syndrome (Sjogren) (M35.0) </option>
<option value="K11.70 Hyposecretion">K11.70 	Hyposecretion </option>
<option value="K11.71 Xerostomia">K11.71 	Xerostomia </option>
<option value="K12 Stomatitis and related lesions">K12 	Stomatitis and related lesions </option>
<option value="K12.0 Recurrent oral aphthae">K12.0	Recurrent oral aphthae </option>
<option value="K12.00 Recurrent (minor) aphthae">K12.00 	Recurrent (minor) aphthae </option>
<option value="Aphthous stomatitis">Aphthous stomatitis</option>
<option value="Minor aphthae">Minor aphthae </option>
<option value="Recurrent aphthous ulcer ">Recurrent aphthous ulcer </option>
<option value="K12.1 Other forms of stomatitis ">K12.1	 Other forms of stomatitis </option>
<option value="K12.12 Denture stomatitis ">K12.12 	Denture stomatitis </option>
<option value="Excludes: denture stomatitis due to candidal jinfection (B37.03)">Excludes: denture stomatitis due to candidal jinfection (B37.03) </option>
<option value="K12.19 Stomatitis, unspecified ">K12.19		Stomatitis, unspecified </option>
<option value="K13 Other diseases of lip and oral mucosa ">K13	 Other diseases of lip and oral mucosa </option>
<option value="K13.7 Other and unspecified lesions of oral mucosa ">K13.7 Other and unspecified lesions of oral mucosa </option>
<option value="K13.71 Oral fistula ">K13.71 	Oral fistula </option>
<option value="Excludes: orontral fistula (T81. 8) ">Excludes: orontral fistula (T81. 8) </option>
<option value="K14 Diseases of tongue ">K14	Diseases of tongue 	</option>
<option value="K14.6 Glossodynia">K14.6 Glossodynia </option>
<option value="K16.49 Glossodynia, unspecified">K16.49 	Glossodynia, unspecified</option>


